### PR TITLE
Require hashable-1.3

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Now that `hashable-1.3` is the minimum version that we support, we can clean up some CPP. In particular, this:

https://github.com/ekmett/semigroups/blob/6c3dcbed31b3ba1ef3ee66126a40758d1d8f452a/src-ghc7/Data/Semigroup.hs#L580-L584

and this:

https://github.com/ekmett/semigroups/blob/6c3dcbed31b3ba1ef3ee66126a40758d1d8f452a/src-ghc7/Data/List/NonEmpty.hs#L194-L198

**Comment by phadej** [comment]
@RyanGlScott good point. I was lazy, with this PR.

**Comment by phadej** [comment]
Done.

**Comment by phadej** [comment]
Also, https://gist.github.com/phadej/da7a09aa06c243c8311c99668d32553b is a small list of ~some packages having upper bounds on `hashable`; there are not all of kmettverse, but at least the `lens` parts. They should be fine with revisions.

**Comment by RyanGlScott** [comment]
Urk. One thing I didn't realize until after I had merged this was that `hashable-1.3` now requires GHC 7.4 or later, which means that `semigroups` will no longer build with GHC 7.0 or 7.2. I suppose this is inevitable?

**Pull request merged**
