### PR TITLE
Add Hashable1 instances

### PR DESCRIPTION
**Pull request by sjakobi**
Corresponding PR for hashable:
https://github.com/tibbe/hashable/pull/187

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Thanks, LGTM. I can pull the trigger on this when the corresponding `hashable` patch gets merged upstream.

**Comment by sjakobi** [comment]
I have added the instances defined in https://github.com/haskell-unordered-containers/hashable/commit/3fcd19a318d8669dc7a63c4814b5233c421ee07b.

**Comment by phadej** [comment]
Looks like you need to have `MIN_VERSION_hashable(something)` to guard when the `Hashable1` become available.

**Comment by sjakobi** [comment]
> Looks like you need to have `MIN_VERSION_hashable(something)` to guard when the `Hashable1` become available.

I had simply forgotten to import `Data.Hashable.Lifted` in `Data.Semigroup`. `semigroups` already has the correct lower bound on `hashable`.

**Comment by RyanGlScott** [comment]
Thanks, @sjakobi!

Is this something you need released urgently? If not, I'll wait until my next batch of Hackage uploads before I make a new release.

**Comment by sjakobi** [comment]
Thanks for the merge!

> Is this something you need released urgently?

Nope. I'm not aware of any projects that need these instances and use GHC < 8.

**Pull request merged**
