### PR TITLE
Allow hashable-1.4

### PR DESCRIPTION
**Pull request by phadej**
I went ahead an made a revision already: https://hackage.haskell.org/package/semigroups-0.19.2/revisions/

### CODE REVIEW

**Comment by phadej** [comment]
I had to undo the revision as:

```
Building library for semigroups-0.19.2..
[1 of 4] Compiling Paths_semigroups ( /code/other-haskell/semigroups/.dist-newstyle-trustee/4e2ae3266d6ed5277978a34da70fd9f18e7d586a9372dd717853e4d03e070a626e969e67a607702dcf69f625f945d2a0ac45944d6494913ba95afe0101de17ef/build/x86_64-linux/ghc-7.8.4/semigroups-0.19.2/noopt/build/autogen/Paths_semigroups.hs, /code/other-haskell/semigroups/.dist-newstyle-trustee/4e2ae3266d6ed5277978a34da70fd9f18e7d586a9372dd717853e4d03e070a626e969e67a607702dcf69f625f945d2a0ac45944d6494913ba95afe0101de17ef/build/x86_64-linux/ghc-7.8.4/semigroups-0.19.2/noopt/build/Paths_semigroups.o )
[2 of 4] Compiling Data.List.NonEmpty ( src-ghc7/Data/List/NonEmpty.hs, /code/other-haskell/semigroups/.dist-newstyle-trustee/4e2ae3266d6ed5277978a34da70fd9f18e7d586a9372dd717853e4d03e070a626e969e67a607702dcf69f625f945d2a0ac45944d6494913ba95afe0101de17ef/build/x86_64-linux/ghc-7.8.4/semigroups-0.19.2/noopt/build/Data/List/NonEmpty.o )
[3 of 4] Compiling Data.Semigroup   ( src-ghc7/Data/Semigroup.hs, /code/other-haskell/semigroups/.dist-newstyle-trustee/4e2ae3266d6ed5277978a34da70fd9f18e7d586a9372dd717853e4d03e070a626e969e67a607702dcf69f625f945d2a0ac45944d6494913ba95afe0101de17ef/build/x86_64-linux/ghc-7.8.4/semigroups-0.19.2/noopt/build/Data/Semigroup.o )


src-ghc7/Data/Semigroup.hs:477:10:
    No instance for (Data.Functor.Classes.Eq1 Min)
      arising from the superclasses of an instance declaration
    In the instance declaration for ‘Hashable1 Min’

src-ghc7/Data/Semigroup.hs:584:10:
    No instance for (Data.Functor.Classes.Eq1 Max)
      arising from the superclasses of an instance declaration
    In the instance declaration for ‘Hashable1 Max’

src-ghc7/Data/Semigroup.hs:775:10:
    No instance for (Data.Functor.Classes.Eq1 First)
      arising from the superclasses of an instance declaration
    In the instance declaration for ‘Hashable1 First’

src-ghc7/Data/Semigroup.hs:866:10:
    No instance for (Data.Functor.Classes.Eq1 Last)
      arising from the superclasses of an instance declaration
    In the instance declaration for ‘Hashable1 Last’

src-ghc7/Data/Semigroup.hs:995:10:
    No instance for (Data.Functor.Classes.Eq1 WrappedMonoid)
      arising from the superclasses of an instance declaration
    In the instance declaration for ‘Hashable1 WrappedMonoid’

src-ghc7/Data/Semigroup.hs:1088:10:
    No instance for (Data.Functor.Classes.Eq1 Option)
      arising from the superclasses of an instance declaration
    In the instance declaration for ‘Hashable1 Option’
```

These types cannot be given `Hashable1` instance (and aren't in `hashable-1.4`) because of the missing `Eq1` instances.

**Comment by phadej** [comment]
We have three options, which both are not fun:
- make a major version of `semigroups` dropping this instances too (very bad)
- Add the missing `Eq1` instances (this is tricky to make them available, but possible)
- Do "nothing". Make a semigroups release which doesn't support older GHCs, so it essentially provides only `Data.Semigroup.Generic`

**Comment by RyanGlScott** [comment]
I'm most inclined to pick the first option and drop the `Hashable1` instances.

**Comment by phadej** [comment]
@RyanGlScott Yes, I think its not that bad, given how tricky is to get 2. right.

**Comment by phadej** [comment]
I update the PR.

**Comment by RyanGlScott** [comment]
Thanks. How are you testing this, out of curiosity? I tried this, but failed:

```
$ cabal build -w ghc-7.10.3 --constraint="hashable==1.4.*" --allow-newer=unordered-containers:hashable --ghc-options="-optl-no-pie"
Build profile: -w ghc-7.10.3 -O1
In order, the following will be built (use -v for more details):
 - unordered-containers-0.2.14.0 (lib) (requires build)
 - semigroups-0.20 (lib) (first run)
Starting     unordered-containers-0.2.14.0 (lib)
Building     unordered-containers-0.2.14.0 (lib)

Failed to build unordered-containers-0.2.14.0.
Build log (
/home/ryanglscott/.cabal/logs/ghc-7.10.3/unordered-containers-0.2.14.0-2736add20206b1713da25baf8ceef919c862b8ab56110af5ed84a1d809cd5963.log
):
Configuring library for unordered-containers-0.2.14.0..
Preprocessing library for unordered-containers-0.2.14.0..
Building library for unordered-containers-0.2.14.0..
[1 of 9] Compiling Data.HashMap.Internal.List ( Data/HashMap/Internal/List.hs, dist/build/Data/HashMap/Internal/List.o )
[2 of 9] Compiling Data.HashMap.Internal.Unsafe ( Data/HashMap/Internal/Unsafe.hs, dist/build/Data/HashMap/Internal/Unsafe.o )
[3 of 9] Compiling Data.HashMap.Internal.Array ( Data/HashMap/Internal/Array.hs, dist/build/Data/HashMap/Internal/Array.o )
[4 of 9] Compiling Data.HashMap.Internal ( Data/HashMap/Internal.hs, dist/build/Data/HashMap/Internal.o )

Data/HashMap/Internal.hs:536:10-48:
    Could not deduce (transformers-0.4.2.0:Data.Functor.Classes.Eq1
                        (HashMap k))
      arising from the superclasses of an instance declaration
    from the context (Hashable k)
      bound by the instance declaration
      at Data/HashMap/Internal.hs:536:10-48
    In the instance declaration for ‘H.Hashable1 (HashMap k)’
cabal: Failed to build unordered-containers-0.2.14.0 (which is required by
semigroups-0.20). See the build log above for details.
```

**Comment by phadej** [comment]
For the record. option 2 looks like:

```diff
diff --git a/semigroups.cabal b/semigroups.cabal
index 0bf45f1..da00c30 100644
--- a/semigroups.cabal
+++ b/semigroups.cabal
@@ -28,7 +28,7 @@ tested-with:   GHC == 7.0.4
              , GHC == 8.8.4
              , GHC == 8.10.7
              , GHC == 9.0.1
-             , GHC == 9.2.*
+             , GHC == 9.2.1
 
 source-repository head
   type: git
@@ -175,7 +175,7 @@ library
       build-depends: text >= 0.10 && < 2
 
     if flag(hashable)
-      build-depends: hashable >= 1.2.5.0  && < 1.4
+      build-depends: hashable >= 1.2.5.0  && < 1.5
 
     if flag(hashable) && flag(unordered-containers)
       build-depends: unordered-containers >= 0.2  && < 0.3
diff --git a/src-ghc7/Data/Semigroup.hs b/src-ghc7/Data/Semigroup.hs
index d40f3aa..0e49bd6 100644
--- a/src-ghc7/Data/Semigroup.hs
+++ b/src-ghc7/Data/Semigroup.hs
@@ -31,6 +31,12 @@
 #define MIN_VERSION_base(x,y,z) 1
 #endif
 
+#ifdef MIN_VERSION_transformers
+#if !(MIN_VERSION_transformers(0,4,0) && !(MIN_VERSION_transformers(0,5,0)))
+#define LIFTER_FUNCTOR_CLASSES 1
+#endif
+#endif
+
 -----------------------------------------------------------------------------
 -- |
 -- Module      :  Data.Semigroup
@@ -156,6 +162,10 @@ import Data.ByteString.Short
 import Data.Functor.Identity
 #endif
 
+#ifdef MIN_VERSION_transformers
+import Data.Functor.Classes (Eq1 (..))
+#endif
+
 #if (MIN_VERSION_base(4,7,0)) || defined(MIN_VERSION_tagged)
 import Data.Proxy
 #endif
@@ -991,6 +1001,16 @@ newtype WrappedMonoid m = WrapMonoid
 instance Hashable a => Hashable (WrappedMonoid a) where
   hashWithSalt p (WrapMonoid a) = hashWithSalt p a
 
+#ifdef MIN_VERSION_transformers
+-- | @since 0.19.3
+instance Eq1 WrappedMonoid where
+#ifdef LIFTER_FUNCTOR_CLASSES
+    liftEq eq (WrapMonoid x) (WrapMonoid y) = eq x y
+#else
+    eq1 = (==)
+#endif
+#endif
+
 -- | @since 0.19.2
 instance Hashable1 WrappedMonoid where
   liftHashWithSalt h salt (WrapMonoid a) = h salt a
```

**Comment by phadej** [comment]
```
% cabal build -w ghc-7.10.3 --constraint='hashable >=1.4'
Resolving dependencies...
Build profile: -w ghc-7.10.3 -O1
In order, the following will be built (use -v for more details):
 - semigroups-0.20 (lib) (first run)
Configuring library for semigroups-0.20..
Preprocessing library for semigroups-0.20..
Building library for semigroups-0.20..
[1 of 4] Compiling Paths_semigroups ( /code/other-haskell/semigroups/dist-newstyle/build/x86_64-linux/ghc-7.10.3/semigroups-0.20/build/autogen/Paths_semigroups.hs, /code/other-haskell/semigroups/dist-newstyle/build/x86_64-linux/ghc-7.10.3/semigroups-0.20/build/Paths_semigroups.o )
[2 of 4] Compiling Data.List.NonEmpty ( src-ghc7/Data/List/NonEmpty.hs, /code/other-haskell/semigroups/dist-newstyle/build/x86_64-linux/ghc-7.10.3/semigroups-0.20/build/Data/List/NonEmpty.o )
[3 of 4] Compiling Data.Semigroup   ( src-ghc7/Data/Semigroup.hs, /code/other-haskell/semigroups/dist-newstyle/build/x86_64-linux/ghc-7.10.3/semigroups-0.20/build/Data/Semigroup.o )

src-ghc7/Data/Semigroup.hs:175:1: Warning:
    The import of ‘Data.Hashable.Lifted’ is redundant
      except perhaps to import instances from ‘Data.Hashable.Lifted’
    To import instances alone, use: import Data.Hashable.Lifted()
[4 of 4] Compiling Data.Semigroup.Generic ( src/Data/Semigroup/Generic.hs, /code/other-haskell/semigroups/dist-newstyle/build/x86_64-linux/ghc-7.10.3/semigroups-0.20/build/Data/Semigroup/Generic.o )
```

The trick is that

```
% cabal-plan
...
PkgId (PkgName "semigroups") (Ver [0,20])
CompNameLib
  base-4.8.2.0
  binary-0.7.5.0
  bytestring-0.10.6.0
  containers-0.5.6.2
  deepseq-1.4.1.1
  hashable-1.4.0.0
  tagged-0.8.6.1
  template-haskell-2.10.0.0
  text-1.2.4.1
  transformers-0.4.2.0
  transformers-compat-0.7.1
  unordered-containers-0.2.5.1
```

**Comment by RyanGlScott** [comment]
Oh, I had assumed that there would be no way the build would work without `--allow-newer=unordered-containers:hashable`. My mistake.

The PR itself looks fine. Do you think we should wait for a resolution on haskell-unordered-containers/unordered-containers#318 before releasing this to Hackage?

**Comment by phadej** [comment]
> Do you think we should wait for a resolution on

Yes, I don't think there is any hurry with a release `hashable-1.4` compatible `semigroups` as the dependency is guarded by `if !Impl(ghc >=8.0)`. 

OTOH, I ifgured as instances are added recently, we can make a relaxed version for `semigroups-0.19.1` (i.e previous release), so there will be install plans with it and `hashable-1.4` for GHC-7.

**Comment by phadej** [comment]
I made that revision: https://hackage.haskell.org/package/semigroups-0.19.1/revisions/ I hope its fine.

**Comment by RyanGlScott** [comment]
Thanks, @phadej! In the meantime, I'll go ahead and merge this.

**Pull request merged**
