### PR TITLE
Add `groupOn`, `groupAllOn`, `groupOn1`, `groupAllOn1`

### PR DESCRIPTION
**Pull request by pseudonom**
`mono-traversable` has the pretty handy [`groupAllOn`](https://hackage.haskell.org/package/mono-traversable-0.9.2.1/docs/Data-Sequences.html#v:groupAllOn) which is often the desired behavior. This PR adds that function and supporting functions to `Data.List.NonEmpty`.

### CODE REVIEW

**Comment by pseudonom** [comment]
Bump

**Comment by ekmett** [comment]
Hrmm. 

The preferred vocabulary for `On` here is `With` to match the combinators in `GHC.Exts` from the ["comprehensive comprehensions"](http://research.microsoft.com/en-us/um/people/simonpj/papers/list-comp/list-comp.pdf) paper. That'd make it so that if you use these with comprehensive comprehensions turned on and `RebindableSyntax` turned on then you'd get these combinators. 

I'll merge, but I'm going to change the convention to match that.

**Comment by ekmett** [comment]
NB: This affects my own `sortOn` combinator as well.

**Comment by pseudonom** [comment]
Sounds good, thanks.

**Pull request merged**
